# Generated by Django 5.2.15 on 2026-06-15 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carts", "0001_initial"),
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrandedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reporter_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="上报人姓名"
                    ),
                ),
                (
                    "reporter_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="上报人电话"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="情况描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "已上报"),
                            ("recycling", "回收中"),
                            ("recycled", "已回收"),
                        ],
                        default="reported",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("reported_at", models.DateTimeField(verbose_name="上报时间")),
                (
                    "recycled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="回收完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stranded_records",
                        to="carts.cart",
                        verbose_name="推车",
                    ),
                ),
                (
                    "report_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stranded_reports",
                        to="stations.servicestation",
                        verbose_name="上报位置服务点",
                    ),
                ),
            ],
            options={
                "verbose_name": "滞留记录",
                "verbose_name_plural": "滞留记录",
                "db_table": "stranded_records",
                "ordering": ["-reported_at"],
            },
        ),
    ]
