# Generated by Django 5.2.15 on 2026-06-15 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cart_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="推车编号"
                    ),
                ),
                (
                    "cart_type",
                    models.CharField(
                        choices=[("standard", "标准款"), ("large", "大号款")],
                        max_length=20,
                        verbose_name="车型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可用"),
                            ("borrowed", "借出中"),
                            ("stranded", "滞留"),
                            ("transferring", "调拨中"),
                            ("cleaning", "清洁中"),
                            ("reset_check", "复位检查中"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="当前状态",
                    ),
                ),
                (
                    "last_clean_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近清洁时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carts",
                        to="stations.servicestation",
                        verbose_name="所属服务点",
                    ),
                ),
            ],
            options={
                "verbose_name": "推车档案",
                "verbose_name_plural": "推车档案",
                "db_table": "carts",
                "ordering": ["-created_at"],
            },
        ),
    ]
