# Generated by Django 5.2.15 on 2026-06-15 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carts", "0003_alter_cart_status"),
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fault_type",
                    models.CharField(
                        choices=[
                            ("wheel", "车轮故障"),
                            ("brake", "刹车故障"),
                            ("seat", "座椅故障"),
                            ("handle", "把手故障"),
                            ("lock", "锁具故障"),
                            ("other", "其他故障"),
                        ],
                        max_length=20,
                        verbose_name="故障类型",
                    ),
                ),
                (
                    "reporter_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="报修人姓名"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="故障描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待维修"),
                            ("repairing", "维修中"),
                            ("completed", "维修完成"),
                            ("scrapped", "已报废"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "repair_result",
                    models.TextField(blank=True, null=True, verbose_name="维修结果"),
                ),
                ("reported_at", models.DateTimeField(verbose_name="报修时间")),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始维修时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_records",
                        to="carts.cart",
                        verbose_name="推车",
                    ),
                ),
                (
                    "report_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_reports",
                        to="stations.servicestation",
                        verbose_name="报修服务点",
                    ),
                ),
            ],
            options={
                "verbose_name": "维修记录",
                "verbose_name_plural": "维修记录",
                "db_table": "maintenance_records",
                "ordering": ["-reported_at"],
            },
        ),
    ]
