# Generated by Django 5.2.15 on 2026-06-15 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carts", "0002_alter_cart_status"),
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="预约单号"
                    ),
                ),
                (
                    "user_phone",
                    models.CharField(max_length=20, verbose_name="预约人手机号"),
                ),
                ("reserve_time", models.DateTimeField(verbose_name="预约时间")),
                ("expire_time", models.DateTimeField(verbose_name="失效时间")),
                (
                    "pickup_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="取车时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "预约中"),
                            ("completed", "已完成"),
                            ("expired", "已失效"),
                            ("cancelled", "已取消"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="预约状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="carts.cart",
                        verbose_name="预约推车",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="stations.servicestation",
                        verbose_name="预约服务点",
                    ),
                ),
            ],
            options={
                "verbose_name": "推车预约记录",
                "verbose_name_plural": "推车预约记录",
                "db_table": "cart_reservations",
                "ordering": ["-reserve_time"],
            },
        ),
    ]
