# Generated by Django 5.2.15 on 2026-06-15 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carts", "0001_initial"),
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rental_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="借用单号"
                    ),
                ),
                (
                    "user_phone",
                    models.CharField(max_length=20, verbose_name="借用人手机号"),
                ),
                ("borrow_time", models.DateTimeField(verbose_name="借出时间")),
                (
                    "return_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="归还时间"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("borrowing", "借用中"),
                            ("returned", "已归还"),
                            ("overdue", "逾期未还"),
                        ],
                        max_length=20,
                        verbose_name="当前环节",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "borrow_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrowed_records",
                        to="stations.servicestation",
                        verbose_name="借出服务点",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="carts.cart",
                        verbose_name="推车",
                    ),
                ),
                (
                    "return_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returned_records",
                        to="stations.servicestation",
                        verbose_name="归还服务点",
                    ),
                ),
            ],
            options={
                "verbose_name": "借还记录",
                "verbose_name_plural": "借还记录",
                "db_table": "rental_records",
                "ordering": ["-created_at"],
            },
        ),
    ]
