# Generated by Django 5.2.15 on 2026-06-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalrecord",
            name="is_overdue",
            field=models.BooleanField(default=False, verbose_name="是否逾期"),
        ),
    ]
