# Generated by Django 5.2.15 on 2026-06-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="服务点名")),
                ("floor", models.IntegerField(verbose_name="楼层")),
                ("location", models.CharField(max_length=255, verbose_name="位置描述")),
                (
                    "safety_stock",
                    models.IntegerField(default=5, verbose_name="安全保有量"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "服务点",
                "verbose_name_plural": "服务点",
                "db_table": "service_stations",
            },
        ),
    ]
