# Generated by Django 5.2.15 on 2026-06-15 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicestation",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stations",
                to="venues.venue",
                verbose_name="所属场地",
            ),
        ),
    ]
