# Generated by Django 5.2.15 on 2026-06-15 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carts", "0001_initial"),
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="调拨单号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待出发"),
                            ("transiting", "运输中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="调拨状态",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "普通"), ("urgent", "紧急")],
                        default="normal",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="carts.cart",
                        verbose_name="推车",
                    ),
                ),
                (
                    "from_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transfers",
                        to="stations.servicestation",
                        verbose_name="源站",
                    ),
                ),
            ],
            options={
                "verbose_name": "跨点调拨单",
                "verbose_name_plural": "跨点调拨单",
                "db_table": "transfer_orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
