# Generated by Django 5.2.15 on 2026-06-15 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carts", "0004_alter_cart_status"),
        ("stations", "0002_servicestation_venue"),
        ("venues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossVenueTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_no",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="跨场地调拨单号"
                    ),
                ),
                ("cart_type", models.CharField(max_length=20, verbose_name="车型")),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "普通"), ("urgent", "紧急")],
                        default="normal",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="数量")),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="调拨原因"),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "transport_status",
                    models.CharField(
                        choices=[
                            ("not_started", "未发货"),
                            ("in_transit", "运输中"),
                            ("arrived", "已到达"),
                            ("confirmed", "已确认收货"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="运输状态",
                    ),
                ),
                (
                    "approver_comment",
                    models.TextField(blank=True, null=True, verbose_name="审批意见"),
                ),
                (
                    "approval_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "transporter",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="运输方/司机",
                    ),
                ),
                (
                    "transport_tracking_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="运输跟踪号"
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发货时间"
                    ),
                ),
                (
                    "arrived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="到达时间"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认收货时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_cross_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cross_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审批人",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cross_venue_transfers",
                        to="carts.cart",
                        verbose_name="推车",
                    ),
                ),
                (
                    "confirmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_cross_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="确认收货操作人",
                    ),
                ),
                (
                    "from_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_cross_transfers",
                        to="stations.servicestation",
                        verbose_name="源服务点",
                    ),
                ),
                (
                    "from_venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_cross_transfers",
                        to="venues.venue",
                        verbose_name="申请场地",
                    ),
                ),
                (
                    "to_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_cross_transfers",
                        to="stations.servicestation",
                        verbose_name="目标服务点",
                    ),
                ),
                (
                    "to_venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_cross_transfers",
                        to="venues.venue",
                        verbose_name="目标场地",
                    ),
                ),
            ],
            options={
                "verbose_name": "跨场地调拨单",
                "verbose_name_plural": "跨场地调拨单",
                "db_table": "cross_venue_transfers",
                "ordering": ["-created_at"],
            },
        ),
    ]
