# Generated by Django 5.2.15 on 2026-06-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="场地名称"
                    ),
                ),
                (
                    "venue_type",
                    models.CharField(
                        choices=[("mall", "商场"), ("park", "园区"), ("other", "其他")],
                        default="mall",
                        max_length=20,
                        verbose_name="场地类型",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="地址")),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="联系人"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "total_floors",
                    models.IntegerField(default=5, verbose_name="总楼层数"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "场地",
                "verbose_name_plural": "场地",
                "db_table": "venues",
                "ordering": ["-created_at"],
            },
        ),
    ]
